version: '3'
services:

  cljrunner:
    build: ./cljrunner
    image: inventi/cljrunner
    volumes:
      - ./work/cljrunner-ws:/var/jenkins-slave
      - ./work/runner-home:/home/jenkins
    depends_on:
      - jenkins
      - jenkins-slave

  javarunner:
    build: ./javarunner
    image: inventi/javarunner
    volumes:
      - ./work/javarunner-ws:/var/jenkins-slave
      - ./work/runner-home:/home/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
      - jenkins-slave

  jenkins:
    image: jenkins
    volumes:
      - ./data/jenkins-home:/var/jenkins_home
    ports:
      - 8080:8080

  jenkins-slave:
    build: ./jenkins-slave
    image: inventi/jenkins-slave
